name: 'Build'

on:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]'
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  phpunit:
    name: 'PHPUnit'
    runs-on: 'ubuntu-24.04'
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: "${{ matrix.php }}"
      - name: 'Composer Install'
        uses: 'ramsey/composer-install@v3'
      - name: 'PHPUnit'
        run: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=phpunit-coverage.xml'
      - uses: 'qltysh/qlty-action/coverage@v2'
        with:
          token: "${{ secrets.QLTY_COVERAGE_TOKEN }}"
          files: 'phpunit-coverage.xml'
          format: 'clover'
