name: 'Build'

on:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]'
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    name: 'Run PHP CS Fixer'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.2'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/php-cs-fixer fix --diff --dry-run --show-progress=none --ansi'

  phpstan:
    name: 'Run PHPStan'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.2'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/phpstan analyze --no-progress --ansi'

  rector:
    name: 'Run Rector'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.2'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/rector process --dry-run --no-progress-bar --ansi'

  composer:
    name: 'Validate composer.json'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.2'
      - run: 'composer validate'

  phpunit:
    name: 'Run PHPUnit'
    runs-on: 'ubuntu-24.04'
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
      fail-fast: false
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: "${{ matrix.php }}"
      - uses: 'ramsey/composer-install@v3'
      - run: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=phpunit-coverage.xml'
      - uses: 'qltysh/qlty-action/coverage@v2'
        with:
          token: "${{ secrets.QLTY_COVERAGE_TOKEN }}"
          files: 'phpunit-coverage.xml'
          format: 'clover'
