name: 'Subtree split'

on:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]'

jobs:
  subtree-split:
    name: 'Subtree split'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'webfactory/ssh-agent@v0.9.0'
        with:
          ssh-private-key: "${{ secrets.DEPLOY_KEY_DOCTRINE_ENHANCED_EVENTS }}"
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - run: 'git remote add doctrine-enhanced-events git@github.com:darkwebdesign/doctrine-enhanced-events.git'
      - run: 'git subtree split --prefix=doctrine-enhanced-events --branch doctrine-enhanced-events'
      - run: "git push doctrine-enhanced-events doctrine-enhanced-events:${GITHUB_REF#refs/heads/}"
